// Firebase configuration - Auto-generated by FlutterFire CLI
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Firebase configuration for all platforms
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Web platform not configured');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError('iOS platform not configured');
      case TargetPlatform.macOS:
        throw UnsupportedError('macOS platform not configured');
      case TargetPlatform.windows:
        throw UnsupportedError('Windows platform not configured');
      case TargetPlatform.linux:
        throw UnsupportedError('Linux platform not configured');
      default:
        throw UnsupportedError('Platform not supported');
    }
  }

  /// Android Firebase configuration (SHA-1 restricted)
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK6KQhqDQqlqo_S-tyjkhI-Y0OYoKaqL0',
    appId: '1:664743099827:android:116b373dcf054c6c2d1fc6',
    messagingSenderId: '664743099827',
    projectId: 'vit-connect-app',
    storageBucket: 'vit-connect-app.firebasestorage.app',
  );
}
