/// Comprehensive Student Report Data Model
/// Contains all academic and personal information for report generation
class StudentReportData {
  // Basic Info
  final String name;
  final String registerNumber;
  final String vitEmail;
  final String? nickname;
  final String? gender;
  final String? dateOfBirth;

  // Academic Profile
  final String program;
  final String branch;
  final String schoolName;
  final String? yearJoined;
  final String? studySystem;
  final String? eduStatus;
  final String? campus;
  final String? programmeMode;

  // Hostel/Mess Info
  final String? hostelBlock;
  final String? roomNumber;
  final String? bedType;
  final String? messName;

  // Academic Performance
  final double cgpa;
  final double creditsRegistered;
  final double creditsEarned;
  final double totalCreditsRequired;
  final int sGrades;
  final int aGrades;
  final int bGrades;
  final int cGrades;
  final int dGrades;
  final int eGrades;
  final int fGrades;
  final int nGrades;

  // Curriculum Progress
  final List<CurriculumProgressData> curriculumProgress;

  // Basket Progress
  final List<BasketProgressData> basketProgress;

  // Semester Performance
  final List<SemesterPerformanceData> semesterPerformances;

  // Grade History
  final List<SemesterGradeData> gradeHistory;

  // Marks History
  final List<SemesterMarksData> marksHistory;

  // Fee Details
  final List<FeeReceiptData> feeReceipts;
  final double totalFeesPaid;

  // Metadata
  final DateTime generatedAt;

  StudentReportData({
    required this.name,
    required this.registerNumber,
    required this.vitEmail,
    this.nickname,
    this.gender,
    this.dateOfBirth,
    required this.program,
    required this.branch,
    required this.schoolName,
    this.yearJoined,
    this.studySystem,
    this.eduStatus,
    this.campus,
    this.programmeMode,
    this.hostelBlock,
    this.roomNumber,
    this.bedType,
    this.messName,
    required this.cgpa,
    required this.creditsRegistered,
    required this.creditsEarned,
    required this.totalCreditsRequired,
    required this.sGrades,
    required this.aGrades,
    required this.bGrades,
    required this.cGrades,
    required this.dGrades,
    required this.eGrades,
    required this.fGrades,
    required this.nGrades,
    required this.curriculumProgress,
    required this.basketProgress,
    required this.semesterPerformances,
    required this.gradeHistory,
    required this.marksHistory,
    required this.feeReceipts,
    required this.totalFeesPaid,
    required this.generatedAt,
  });

  /// Convert to JSON for export
  Map<String, dynamic> toJson() {
    return {
      'metadata': {
        'generated_at': generatedAt.toIso8601String(),
        'generated_by': 'VIT Verse',
        'organization_link': 'https://github.com/vit-verse/',
        'tagline':
            'VIT Verse is a student-driven, open-source organization dedicated to building reliable, secure, and thoughtfully designed digital tools for VIT University students.',
        'disclaimer':
            'This report is generated by VIT Verse app and is not official. It is not affiliated with VIT Chennai.',
      },
      'basic_info': {
        'name': name,
        'register_number': registerNumber,
        'vit_email': vitEmail,
        'nickname': nickname,
        'gender': gender,
        'date_of_birth': dateOfBirth,
      },
      'academic_profile': {
        'program': program,
        'branch': branch,
        'school_name': schoolName,
        'year_joined': yearJoined,
        'study_system': studySystem,
        'educational_status': eduStatus,
        'campus': campus,
        'programme_mode': programmeMode,
      },
      'hostel_mess_info': {
        'hostel_block': hostelBlock,
        'room_number': roomNumber,
        'bed_type': bedType,
        'mess_name': messName,
      },
      'academic_performance': {
        'cgpa': cgpa,
        'credits_registered': creditsRegistered,
        'credits_earned': creditsEarned,
        'total_credits_required': totalCreditsRequired,
        'total_courses': totalCourses,
        'pass_percentage': passPercentage,
        'grade_distribution': {
          'S': sGrades,
          'A': aGrades,
          'B': bGrades,
          'C': cGrades,
          'D': dGrades,
          'E': eGrades,
          'F': fGrades,
          'N': nGrades,
        },
      },
      'curriculum_progress': curriculumProgress.map((c) => c.toJson()).toList(),
      'basket_progress': basketProgress.map((b) => b.toJson()).toList(),
      'semester_performances':
          semesterPerformances.map((s) => s.toJson()).toList(),
      'grade_history': gradeHistory.map((g) => g.toJson()).toList(),
      'marks_history': marksHistory.map((m) => m.toJson()).toList(),
      'fee_details': {
        'total_fees_paid': totalFeesPaid,
        'receipts': feeReceipts.map((f) => f.toJson()).toList(),
      },
    };
  }

  int get totalCourses =>
      sGrades +
      aGrades +
      bGrades +
      cGrades +
      dGrades +
      eGrades +
      fGrades +
      nGrades;

  double get passPercentage {
    if (totalCourses == 0) return 0.0;
    final passed = totalCourses - fGrades - nGrades;
    return (passed / totalCourses) * 100;
  }
}

class CurriculumProgressData {
  final String distributionType;
  final double creditsRequired;
  final double creditsEarned;
  final double completionPercentage;

  CurriculumProgressData({
    required this.distributionType,
    required this.creditsRequired,
    required this.creditsEarned,
    required this.completionPercentage,
  });

  Map<String, dynamic> toJson() {
    return {
      'distribution_type': distributionType,
      'credits_required': creditsRequired,
      'credits_earned': creditsEarned,
      'completion_percentage': completionPercentage,
    };
  }
}

class BasketProgressData {
  final String basketTitle;
  final double creditsRequired;
  final double creditsEarned;
  final double completionPercentage;

  BasketProgressData({
    required this.basketTitle,
    required this.creditsRequired,
    required this.creditsEarned,
    required this.completionPercentage,
  });

  Map<String, dynamic> toJson() {
    return {
      'basket_title': basketTitle,
      'credits_required': creditsRequired,
      'credits_earned': creditsEarned,
      'completion_percentage': completionPercentage,
    };
  }
}

class SemesterPerformanceData {
  final String semesterId;
  final String semesterName;
  final double gpa;
  final int courseCount;
  final double totalCredits;
  final List<String> grades;

  SemesterPerformanceData({
    required this.semesterId,
    required this.semesterName,
    required this.gpa,
    required this.courseCount,
    required this.totalCredits,
    required this.grades,
  });

  Map<String, dynamic> toJson() {
    return {
      'semester_id': semesterId,
      'semester_name': semesterName,
      'gpa': gpa,
      'course_count': courseCount,
      'total_credits': totalCredits,
      'grades': grades,
    };
  }
}

class SemesterGradeData {
  final String semesterName;
  final double semesterGpa;
  final int totalCourses;
  final int passedCourses;
  final double totalCredits;
  final List<CourseGradeData> courses;

  SemesterGradeData({
    required this.semesterName,
    required this.semesterGpa,
    required this.totalCourses,
    required this.passedCourses,
    required this.totalCredits,
    required this.courses,
  });

  Map<String, dynamic> toJson() {
    return {
      'semester_name': semesterName,
      'semester_gpa': semesterGpa,
      'total_courses': totalCourses,
      'passed_courses': passedCourses,
      'total_credits': totalCredits,
      'courses': courses.map((c) => c.toJson()).toList(),
    };
  }
}

class CourseGradeData {
  final String courseCode;
  final String courseTitle;
  final String grade;
  final double credits;
  final String courseType;
  final double totalMarks;

  CourseGradeData({
    required this.courseCode,
    required this.courseTitle,
    required this.grade,
    required this.credits,
    required this.courseType,
    required this.totalMarks,
  });

  Map<String, dynamic> toJson() {
    return {
      'course_code': courseCode,
      'course_title': courseTitle,
      'grade': grade,
      'credits': credits,
      'course_type': courseType,
      'total_marks': totalMarks,
    };
  }
}

class SemesterMarksData {
  final String semesterName;
  final List<CourseMarksData> courses;

  SemesterMarksData({required this.semesterName, required this.courses});

  Map<String, dynamic> toJson() {
    return {
      'semester_name': semesterName,
      'courses': courses.map((c) => c.toJson()).toList(),
    };
  }
}

class CourseMarksData {
  final String courseCode;
  final String courseTitle;
  final List<AssessmentData> assessments;
  final double overallPercentage;

  CourseMarksData({
    required this.courseCode,
    required this.courseTitle,
    required this.assessments,
    required this.overallPercentage,
  });

  Map<String, dynamic> toJson() {
    return {
      'course_code': courseCode,
      'course_title': courseTitle,
      'assessments': assessments.map((a) => a.toJson()).toList(),
      'overall_percentage': overallPercentage,
    };
  }
}

class AssessmentData {
  final String title;
  final double score;
  final double maxScore;
  final double percentage;

  AssessmentData({
    required this.title,
    required this.score,
    required this.maxScore,
    required this.percentage,
  });

  Map<String, dynamic> toJson() {
    return {
      'title': title,
      'score': score,
      'max_score': maxScore,
      'percentage': percentage,
    };
  }
}

class FeeReceiptData {
  final String receiptNumber;
  final DateTime? date;
  final String description;
  final double amount;
  final String mode;

  FeeReceiptData({
    required this.receiptNumber,
    this.date,
    required this.description,
    required this.amount,
    required this.mode,
  });

  Map<String, dynamic> toJson() {
    String formattedDate = '';
    if (date != null) {
      formattedDate = '${date!.day}/${date!.month}/${date!.year}';
    }
    return {
      'receipt_number': receiptNumber,
      'date': formattedDate,
      'description': description,
      'amount': amount,
      'mode': mode,
    };
  }
}
